import type { Report } from "./types";

/**
 * Programmatic PDF generation using jsPDF.
 * Draws text, shapes, and colors directly — no DOM rendering dependency.
 * Works identically in dev/prod, dark/light mode.
 */
export async function generateReportPdf(report: Report): Promise<void> {
  const { jsPDF } = await import("jspdf");

  const pdf = new jsPDF("portrait", "mm", "a4");
  const pageW = 210;
  const pageH = 297;
  const marginL = 16;
  const marginR = 16;
  const contentW = pageW - marginL - marginR;
  let y = 0;

  // ─── Color palette ───
  const C = {
    primary: [15, 23, 42] as [number, number, number],       // slate-900
    accent: [59, 130, 246] as [number, number, number],      // blue-500
    accentLight: [239, 246, 255] as [number, number, number],// blue-50
    success: [34, 197, 94] as [number, number, number],      // green-500
    successBg: [240, 253, 244] as [number, number, number],  // green-50
    warning: [245, 158, 11] as [number, number, number],     // amber-500
    warningBg: [255, 251, 235] as [number, number, number],  // amber-50
    danger: [239, 68, 68] as [number, number, number],       // red-500
    dangerBg: [254, 242, 242] as [number, number, number],   // red-50
    text: [15, 23, 42] as [number, number, number],
    textMuted: [100, 116, 139] as [number, number, number],  // slate-500
    cardBg: [248, 250, 252] as [number, number, number],     // slate-50
    border: [226, 232, 240] as [number, number, number],     // slate-200
    white: [255, 255, 255] as [number, number, number],
    headerGradientStart: [30, 64, 175] as [number, number, number], // blue-800
    headerGradientEnd: [79, 70, 229] as [number, number, number],   // indigo-600
  };

  // ─── Helpers ───
  function addFooter(pageNum: number) {
    pdf.setFillColor(...C.border);
    pdf.rect(0, pageH - 12, pageW, 0.3, "F");
    pdf.setFontSize(7);
    pdf.setTextColor(...C.textMuted);
    pdf.text(`Page ${pageNum}`, marginL, pageH - 5);
    pdf.text("Generated by Decisely — decisely.vercel.app", pageW - marginR, pageH - 5, { align: "right" });
  }

  let currentPage = 1;

  function checkPage(needed: number) {
    if (y + needed > pageH - 20) {
      addFooter(currentPage);
      pdf.addPage();
      currentPage++;
      y = 16;
    }
  }

  function drawRoundedRect(x: number, yPos: number, w: number, h: number, r: number, fill: [number, number, number], stroke?: [number, number, number]) {
    pdf.setFillColor(...fill);
    if (stroke) {
      pdf.setDrawColor(...stroke);
      pdf.setLineWidth(0.3);
      pdf.roundedRect(x, yPos, w, h, r, r, "FD");
    } else {
      pdf.roundedRect(x, yPos, w, h, r, r, "F");
    }
  }

  function drawBadge(x: number, yPos: number, text: string, bg: [number, number, number], fg: [number, number, number]) {
    pdf.setFontSize(7);
    const tw = pdf.getTextWidth(text) + 6;
    drawRoundedRect(x, yPos, tw, 5.5, 1.5, bg);
    pdf.setTextColor(...fg);
    pdf.setFont("helvetica", "bold");
    pdf.text(text, x + 3, yPos + 4);
    return tw;
  }

  function wrapText(text: string, maxWidth: number, fontSize: number): string[] {
    pdf.setFontSize(fontSize);
    const words = text.split(" ");
    const lines: string[] = [];
    let current = "";
    for (const word of words) {
      const test = current ? `${current} ${word}` : word;
      if (pdf.getTextWidth(test) > maxWidth) {
        if (current) lines.push(current);
        current = word;
      } else {
        current = test;
      }
    }
    if (current) lines.push(current);
    return lines;
  }

  // ═════════════════════════════════════════════════
  // PAGE 1 — HEADER
  // ═════════════════════════════════════════════════

  // Gradient header bar
  const headerH = 44;
  for (let i = 0; i < headerH; i++) {
    const ratio = i / headerH;
    const r = Math.round(C.headerGradientStart[0] + (C.headerGradientEnd[0] - C.headerGradientStart[0]) * ratio);
    const g = Math.round(C.headerGradientStart[1] + (C.headerGradientEnd[1] - C.headerGradientStart[1]) * ratio);
    const b = Math.round(C.headerGradientStart[2] + (C.headerGradientEnd[2] - C.headerGradientStart[2]) * ratio);
    pdf.setFillColor(r, g, b);
    pdf.rect(0, i * (headerH / headerH), pageW, 1.1, "F");
  }

  // Brand name
  pdf.setTextColor(...C.white);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.text("Decisely", marginL, 18);
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");
  pdf.text("AI-Powered Decision Intelligence", marginL, 25);

  // Domain badge + date (top right)
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "bold");
  const domainLabel = (report.domain || "General").charAt(0).toUpperCase() + (report.domain || "general").slice(1);
  pdf.text(domainLabel.toUpperCase(), pageW - marginR, 16, { align: "right" });
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(7);
  const dateStr = report.createdAt
    ? new Date(report.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  pdf.text(dateStr, pageW - marginR, 22, { align: "right" });

  // Thin accent line under header
  pdf.setFillColor(...C.accent);
  pdf.rect(0, headerH, pageW, 1.2, "F");

  y = headerH + 10;

  // ─── Report Title (Scenario) ───
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(13);
  pdf.setTextColor(...C.text);
  const scenarioLines = wrapText(report.scenario || "Decision Analysis Report", contentW, 13);
  for (const line of scenarioLines) {
    checkPage(7);
    pdf.text(line, marginL, y);
    y += 6;
  }
  y += 4;

  // ═════════════════════════════════════════════════
  // RECOMMENDATION CARD
  // ═════════════════════════════════════════════════
  const rec = report.result;
  if (rec) {
    const recLines = wrapText(rec.recommendation, contentW - 16, 11);
    const recCardH = 18 + recLines.length * 5.5 + (rec.recommendedOption ? 10 : 0);
    checkPage(recCardH + 5);

    drawRoundedRect(marginL, y, contentW, recCardH, 3, C.accentLight, C.accent);

    // Label
    pdf.setFontSize(7);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...C.accent);
    pdf.text("FINAL RECOMMENDATION", marginL + 8, y + 7);

    // Recommendation text
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...C.text);
    let recY = y + 14;
    for (const line of recLines) {
      pdf.text(line, marginL + 8, recY);
      recY += 5.5;
    }

    // Recommended option badge
    if (rec.recommendedOption) {
      recY += 1;
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...C.textMuted);
      pdf.text("Best option: ", marginL + 8, recY);
      const prefixW = pdf.getTextWidth("Best option: ");
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...C.success);
      pdf.text(rec.recommendedOption, marginL + 8 + prefixW, recY);
    }

    y += recCardH + 8;

    // ─── Insight & Why This Works ───
    const sections = [
      { title: "Strategic Insight", body: rec.insight, accent: C.accent, bg: C.accentLight },
      { title: "Why This Works", body: rec.whyThisWorks, accent: C.warning, bg: C.warningBg },
    ];

    for (const sec of sections) {
      if (!sec.body) continue;
      const bodyLines = wrapText(sec.body, contentW - 16, 9);
      const cardH = 16 + bodyLines.length * 4.5;
      checkPage(cardH + 5);

      drawRoundedRect(marginL, y, contentW, cardH, 3, sec.bg);

      // Accent bar left
      pdf.setFillColor(...sec.accent);
      pdf.roundedRect(marginL, y, 2.5, cardH, 1.5, 1.5, "F");

      // Title
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...sec.accent);
      pdf.text(sec.title.toUpperCase(), marginL + 8, y + 7);

      // Body
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...C.text);
      let bY = y + 14;
      for (const line of bodyLines) {
        pdf.text(line, marginL + 8, bY);
        bY += 4.5;
      }

      y += cardH + 6;
    }

    // ═════════════════════════════════════════════════
    // OPTION BREAKDOWN
    // ═════════════════════════════════════════════════
    checkPage(12);
    pdf.setFillColor(...C.border);
    pdf.rect(marginL, y, contentW, 0.3, "F");
    y += 6;

    pdf.setFontSize(13);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...C.text);
    pdf.text("Option Breakdown", marginL, y);
    y += 8;

    for (const opt of rec.options) {
      const isRecommended = opt.option === rec.recommendedOption;

      // ─── Option card ───
      const optTitleLines = wrapText(opt.option, contentW - 20, 11);
      const prosLines = opt.pros.map(p => wrapText(p, (contentW - 24) / 2 - 4, 8));
      const consLines = opt.cons.map(c => wrapText(c, (contentW - 24) / 2 - 4, 8));
      const maxProsH = prosLines.reduce((sum, l) => sum + l.length * 4 + 2, 0) + 8;
      const maxConsH = consLines.reduce((sum, l) => sum + l.length * 4 + 2, 0) + 8;
      const prosConsH = Math.max(maxProsH, maxConsH);

      // Analysis
      const analysisLines = wrapText(opt.detailedAnalysis, contentW - 20, 8);
      const analysisH = analysisLines.length * 4 + 10;

      const cardH = (optTitleLines.length * 6) + 22 + 18 + prosConsH + analysisH;
      checkPage(cardH + 8);

      const borderColor = isRecommended ? C.success : C.border;
      drawRoundedRect(marginL, y, contentW, cardH, 3, C.white, borderColor);

      // Recommended highlight bar
      if (isRecommended) {
        pdf.setFillColor(...C.success);
        pdf.rect(marginL + 0.15, y + 0.15, contentW - 0.3, 2, "F");
      }

      let oY = y + (isRecommended ? 8 : 6);

      // Recommended badge
      if (isRecommended) {
        drawBadge(marginL + 8, oY, "★ BEST CHOICE", C.successBg, C.success);
        oY += 8;
      }

      // Option title
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...C.text);
      for (const line of optTitleLines) {
        pdf.text(line, marginL + 8, oY);
        oY += 6;
      }
      oY += 4;

      // Metrics row
      const metricsY = oY;
      drawRoundedRect(marginL + 6, metricsY, contentW - 12, 14, 2, C.cardBg);

      // Success probability
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...C.textMuted);
      pdf.text("SUCCESS", marginL + 10, metricsY + 5);
      pdf.setFontSize(12);
      pdf.setTextColor(...C.text);
      pdf.text(`${opt.successProbability}%`, marginL + 10, metricsY + 11);

      // Progress bar for probability
      const barX = marginL + 32;
      const barW = 40;
      pdf.setFillColor(...C.border);
      pdf.roundedRect(barX, metricsY + 8, barW, 2.5, 1, 1, "F");
      const fillColor = opt.successProbability >= 70 ? C.success : opt.successProbability >= 40 ? C.warning : C.danger;
      pdf.setFillColor(...fillColor);
      pdf.roundedRect(barX, metricsY + 8, barW * (opt.successProbability / 100), 2.5, 1, 1, "F");

      // Risk badge
      const riskColors: Record<string, { bg: [number, number, number]; fg: [number, number, number] }> = {
        Low: { bg: C.successBg, fg: C.success },
        Medium: { bg: C.warningBg, fg: C.warning },
        High: { bg: C.dangerBg, fg: C.danger },
      };
      const riskStyle = riskColors[opt.riskLevel] || riskColors.Medium;
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...C.textMuted);
      pdf.text("RISK", marginL + 90, metricsY + 5);
      drawBadge(marginL + 90, metricsY + 7, opt.riskLevel, riskStyle.bg, riskStyle.fg);

      // Reward badge
      const rewardStyle = riskColors[opt.rewardLevel] || riskColors.Medium;
      pdf.setTextColor(...C.textMuted);
      pdf.text("REWARD", marginL + 120, metricsY + 5);
      drawBadge(marginL + 120, metricsY + 7, opt.rewardLevel, rewardStyle.bg, rewardStyle.fg);

      oY = metricsY + 18;

      // Pros & Cons side by side
      const halfW = (contentW - 20) / 2;

      // Pros
      drawRoundedRect(marginL + 6, oY, halfW, prosConsH, 2, C.successBg);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...C.success);
      pdf.text("✓ Pros", marginL + 10, oY + 6);
      let pY = oY + 12;
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...C.text);
      pdf.setFontSize(8);
      for (const lines of prosLines) {
        for (let i = 0; i < lines.length; i++) {
          pdf.text(i === 0 ? `• ${lines[i]}` : `  ${lines[i]}`, marginL + 10, pY);
          pY += 4;
        }
        pY += 1;
      }

      // Cons
      drawRoundedRect(marginL + 8 + halfW, oY, halfW, prosConsH, 2, C.dangerBg);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...C.danger);
      pdf.text("✗ Cons", marginL + 12 + halfW, oY + 6);
      let cY = oY + 12;
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...C.text);
      pdf.setFontSize(8);
      for (const lines of consLines) {
        for (let i = 0; i < lines.length; i++) {
          pdf.text(i === 0 ? `• ${lines[i]}` : `  ${lines[i]}`, marginL + 12 + halfW, cY);
          cY += 4;
        }
        cY += 1;
      }

      oY += prosConsH + 4;

      // Detailed analysis
      drawRoundedRect(marginL + 6, oY, contentW - 12, analysisH, 2, C.cardBg);
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...C.accent);
      pdf.text("EVALUATION", marginL + 10, oY + 6);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(...C.text);
      let aY = oY + 12;
      for (const line of analysisLines) {
        pdf.text(line, marginL + 10, aY);
        aY += 4;
      }

      y += cardH + 8;
    }
  }

  // ─── Final footer on last page ───
  addFooter(currentPage);

  // ─── Download ───
  const filename = `decisely-${report.domain || "report"}-${report.id.slice(0, 8)}.pdf`;
  pdf.save(filename);
}
